// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIUbnbuyaQRHGnzRMxU6NfAySRd5c8UeM',
    appId: '1:934811114997:web:d63bc4d79cd1d5eb01d4bc',
    messagingSenderId: '934811114997',
    projectId: 'mobile-health-app-tambag',
    authDomain: 'mobile-health-app-tambag.firebaseapp.com',
    storageBucket: 'mobile-health-app-tambag.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxEYAI3KaKHN2bxH-NyXb7dhKPzazWRaI',
    appId: '1:934811114997:android:c8e5e837b6a011b701d4bc',
    messagingSenderId: '934811114997',
    projectId: 'mobile-health-app-tambag',
    storageBucket: 'mobile-health-app-tambag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCztcFZWgTVQ-dxPdgKakjKHqkWjFDxtEg',
    appId: '1:934811114997:ios:2783da303619cd1401d4bc',
    messagingSenderId: '934811114997',
    projectId: 'mobile-health-app-tambag',
    storageBucket: 'mobile-health-app-tambag.appspot.com',
    iosBundleId: 'com.example.mobileHealthAppTambag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCztcFZWgTVQ-dxPdgKakjKHqkWjFDxtEg',
    appId: '1:934811114997:ios:20d678883f99fdf001d4bc',
    messagingSenderId: '934811114997',
    projectId: 'mobile-health-app-tambag',
    storageBucket: 'mobile-health-app-tambag.appspot.com',
    iosBundleId: 'com.example.mobileHealthAppTambag.RunnerTests',
  );
}
